Repository Teradata/covalent-resources, pull requests merged in 2019-06, with the labels that each got.

#29 feat(): layout card over
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/layouts/card-over/card-over.component.html
  src/app/layouts/card-over/card-over.component.scss
  src/app/layouts/card-over/card-over.component.ts
  src/data.ts
Labels: UX LGTM, ready for merge

#16 chore(): upgrade version
  .gitattributes
  README.md
  package-lock.json
  package.json
  src/app/app.module.ts
  src/config/interceptors/request.interceptor.ts
  yarn.lock
Labels: ready for merge

#26 feat(): layout nav view
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/layouts/nav-view/nav-view.component.html
  src/app/layouts/nav-view/nav-view.component.scss
  src/app/layouts/nav-view/nav-view.component.ts
  src/data.ts
Labels: Code LGTM, UX LGTM, ready for merge

#28 feat(): layout nav list
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/layouts/nav-list/nav-list.component.html
  src/app/layouts/nav-list/nav-list.component.scss
  src/app/layouts/nav-list/nav-list.component.ts
  src/data.ts
Labels: Code LGTM, UX LGTM, ready for merge

#27 feat(): layout management list
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/layouts/manage-list/manage-list.component.html
  src/app/layouts/manage-list/manage-list.component.scss
  src/app/layouts/manage-list/manage-list.component.ts
  src/app/layouts/nav-list/nav-list.component.ts
  src/data.ts
Labels: Code LGTM, UX LGTM, ready for merge

#17 feat(): design pattern creation flow
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/patterns/creation-flow/creation-dialog/creation-dialog-content.html
  src/app/patterns/creation-flow/creation-dialog/creation-dialog.component.html
  src/app/patterns/creation-flow/creation-dialog/creation-dialog.component.scss
  src/app/patterns/creation-flow/creation-dialog/creation-dialog.component.ts
  src/app/patterns/creation-flow/creation-edit/creation-edit.component.html
  src/app/patterns/creation-flow/creation-edit/creation-edit.component.scss
  src/app/patterns/creation-flow/creation-edit/creation-edit.component.ts
  src/app/patterns/creation-flow/creation-flow.component.html
  src/app/patterns/creation-flow/creation-flow.component.scss
  src/app/patterns/creation-flow/creation-flow.component.ts
  src/app/patterns/creation-flow/creation-over-edit/creation-over-edit.component.html
  src/app/patterns/creation-flow/creation-over-edit/creation-over-edit.component.scss
  src/app/patterns/creation-flow/creation-over-edit/creation-over-edit.component.ts
  src/app/patterns/creation-flow/creation-over/creation-over.component.html
  src/app/patterns/creation-flow/creation-over/creation-over.component.scss
  src/app/patterns/creation-flow/creation-over/creation-over.component.ts
  src/app/patterns/creation-flow/creation-sidesheet/creation-sidesheet.component.html
  src/app/patterns/creation-flow/creation-sidesheet/creation-sidesheet.component.scss
  src/app/patterns/creation-flow/creation-sidesheet/creation-sidesheet.component.ts
  src/data.ts
Labels: Code LGTM, UX LGTM

#19 feat(): design patterns stepper form
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/patterns/stepper/stepper.component.html
  src/app/patterns/stepper/stepper.component.scss
  src/app/patterns/stepper/stepper.component.ts
  src/data.ts
Labels: UX LGTM, ready for review

#24 feat(): design pattern empty state
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/patterns/empty-state/empty-content/empty-content.component.html
  src/app/patterns/empty-state/empty-content/empty-content.component.scss
  src/app/patterns/empty-state/empty-content/empty-content.component.spec.ts
  src/app/patterns/empty-state/empty-content/empty-content.component.ts
  src/app/patterns/empty-state/empty-filter/empty-filter.component.html
  src/app/patterns/empty-state/empty-filter/empty-filter.component.scss
  src/app/patterns/empty-state/empty-filter/empty-filter.component.spec.ts
  src/app/patterns/empty-state/empty-filter/empty-filter.component.ts
  src/app/patterns/empty-state/empty-state.component.html
  src/app/patterns/empty-state/empty-state.component.scss
  src/app/patterns/empty-state/empty-state.component.spec.ts
  src/app/patterns/empty-state/empty-state.component.ts
  src/data.ts
Labels: UX LGTM, ready for review

#22 feat(): design pattern nav drawer
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/patterns/nav-drawer/nav-drawer.component.html
  src/app/patterns/nav-drawer/nav-drawer.component.scss
  src/app/patterns/nav-drawer/nav-drawer.component.spec.ts
  src/app/patterns/nav-drawer/nav-drawer.component.ts
  src/data.ts
Labels: UX LGTM, ready for review

#21 feat(): design pattern alerts
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/patterns/alerts/alerts-inline/alerts-inline.component.html
  src/app/patterns/alerts/alerts-inline/alerts-inline.component.scss
  src/app/patterns/alerts/alerts-inline/alerts-inline.component.ts
  src/app/patterns/alerts/alerts-toasts/alerts-toasts.component.html
  src/app/patterns/alerts/alerts-toasts/alerts-toasts.component.scss
  src/app/patterns/alerts/alerts-toasts/alerts-toasts.component.spec.ts
  src/app/patterns/alerts/alerts-toasts/alerts-toasts.component.ts
  src/app/patterns/alerts/alerts.component.html
  src/app/patterns/alerts/alerts.component.scss
  src/app/patterns/alerts/alerts.component.ts
  src/data.ts
Labels: Code LGTM, UX LGTM, ready for merge
